# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.CharField(max_length=80)),
                ('Nationality', models.CharField(max_length=10)),
                ('Phone', models.IntegerField()),
                ('Registration_type', models.CharField(choices=[('Painter', 'Painter'), ('Buyer', 'Buyer')], max_length=23)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
