# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='painter_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='painter',
            name='painting_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='painter',
            name='painting_prize',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='painter',
            name='painting_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='painter',
            name='painting_type',
            field=models.CharField(max_length=30),
        ),
    ]
