# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintermodule', '0002_auto_20181018_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='painting_size',
            field=models.IntegerField(default=40),
        ),
    ]
