# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 01:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=40)),
                ('painting_type', models.CharField(max_length=30)),
                ('painting_size', models.IntegerField(default=40)),
                ('painter_name', models.CharField(max_length=80)),
                ('painting_prize', models.FloatField()),
                ('painting_picture', models.ImageField(upload_to='media/pic')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='user.username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
